import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/@components/pages/Header/Header";
import Footer from "@/@components/pages/Footer/Footer";
import "material-icons/iconfont/material-icons.css";
import NavBar from "@/@components/pages/Header/NavBar";
import { GlobalProvider } from "@/@components/pages/Context/GlobalContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full mx-auto`}
      >
        <GlobalProvider>
          <div className="!w-[100%]">
            <div className="sticky top-0 z-50">
              <Header />
            </div>
            <NavBar />
            <div className="bg-gray-100 2xl:p-0 p-3">{children}</div>
            <div className="bg-black min-h-[40vh]">
              <Footer />
            </div>
          </div>
        </GlobalProvider>
      </body>
    </html>
  );
}
